# Generated by Django 5.1.1 on 2024-09-10 19:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(max_length=80, verbose_name='Apellidos')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(max_length=20, verbose_name='Nombre')),
                ('direccion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Documento')),
                ('tipo_genero', models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('FEM', 'Femenino'), ('MASC', 'Masculino'), ('OTRO', 'Otro')], max_length=4)),
                ('tipo_documento', models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extrangería'), ('NIT', 'Número de Identificación Tributaria (NIT)'), ('TI', 'Tarjeta de identidad')], max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60, unique=True, verbose_name='Nombre')),
                ('precio', models.IntegerField(null=True)),
                ('cantidad', models.IntegerField(null=True)),
            ],
        ),
    ]
