# Generated by Django 5.1.1 on 2024-09-10 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_producto_presentacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='tipo_genero',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='presentacion',
        ),
    ]
