# Generated by Django 5.1.1 on 2024-09-11 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_persona_tipo_genero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(default='', max_length=80, verbose_name='Nombres')),
                ('apellidos', models.CharField(default='', max_length=80, verbose_name='Apellidos')),
                ('documento', models.CharField(default='', max_length=20, verbose_name='Documento')),
                ('fecha_nacimiento', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de nacimiento')),
                ('telefono', models.CharField(default='', max_length=20, verbose_name='Teléfono')),
                ('direccion', models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='Dirección')),
                ('tipo_documento', models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extrangería'), ('NIT', 'Número de Identificación Tributaria (NIT)'), ('TI', 'Tarjeta de identidad')], default='', max_length=4)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['id'],
            },
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['id'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(default='', max_length=100, verbose_name='Presentación'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=60, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='Producto',
        ),
    ]
