# Generated by Django 5.1.1 on 2024-09-11 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_cliente_delete_persona_alter_producto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Presentación'),
        ),
    ]
