# Generated by Django 5.1.1 on 2024-09-11 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_producto_nombre_alter_producto_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='presentacion',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Presentacion'),
        ),
    ]
