# Generated by Django 5.1.1 on 2024-10-09 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_producto_presentacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='documento',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(default='', max_length=20, unique=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('', 'Seleccione una opción'), ('CC', 'Cédula de ciudadanía'), ('CE', 'Cédula de extrangería'), ('NIT', 'Número de Identificación Tributaria (NIT)'), ('TI', 'Tarjeta de identidad')], default='', max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=60, unique=True, verbose_name='Nombre'),
        ),
    ]
