# Generated by Django 5.1.1 on 2024-10-09 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_cliente_documento_alter_cliente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='', max_length=60, verbose_name='Nombre'),
        ),
    ]
